version: "3"

server:
  command: "php vendor/bin/roadrunner-worker"

rpc:
  listen: tcp://127.0.0.1:6001

http:
  address: 0.0.0.0:8000
  middleware: ["static"]
  static:
    dir: "public"
    forbid: [".php", ".htaccess"]
  pool:
    num_workers: 2
    max_jobs: 500
    supervisor:
      exec_ttl: 30s
  http2:
    h2c: false
    max_concurrent_streams: 128

logs:
  mode: production
  level: debug
  output: stdout
  encoding: json
